### PR TITLE
Fixing a typo 

### LINKED ISSUE #116: Ratiation or Radiation
I saw this a lot in the code and I thought it was a typo... but then I see it even here:

https://github.com/OceanBioME/OceanBioME.jl/blob/2815e3633cc16a2a7bb732bdd85b1b4768330326/src/Light/2band.jl#L1

Is it a typo or a term I am not aware of?

If it's actually legit then note I may have replaced some with `radiation` in the docs...

### PR DESCRIPTION
**Pull request by jagoosw**
closes #116

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
If you add to the first comment of this PR "closes #116" then when the PR merges the issue will close as well.

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
@jagoosw can you give me full organization rights (I can't see the organization settings) -- I'll try to figure out the TagBot situation.

**Comment by johnryantaylor** [comment]
Thanks Navid, I sent an invitation to the organization with Manage rights.  Will that let you do this?

**Comment by navidcy** [comment]
> Thanks Navid, I sent an invitation to the organization with Manage rights.  Will that let you do this?

 I still don't see organization rights. :(

**Comment by johnryantaylor** [comment]
Ok, I gave you owner-level permission - can you try again? (strange that the Manage role isn’t sufficient)

**Pull request merged**
