### PR TITLE
Fixed some `show` methods

### PR DESCRIPTION
**Pull request by jagoosw**
When I went to update Oceananigans I found these changes I made so thought we might as well merge them first too.

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
lgtm

**Comment by navidcy** [comment]
We dropped showing "Optional components" and "Sinking velocities" from model's show methods?

**Comment by jagoosw** [comment]
> We dropped showing "Optional components" and "Sinking velocities" from model's show methods?

Where is this?

**Comment by navidcy** [comment]
E.g., look at the changes in `docs/src/model_components/biogeochemical/LOBSTER.md` I had to do so that the doctests pass. That's what I meant.

**Comment by jagoosw** [comment]
Ah I see, that's because there `LOBSTER` is wrapped in `Biogeochemistry` so its only showing the summary of the underlying model:
```julia
julia> bgc_model
Lodyc-DAMTP Ocean Biogeochemical Simulation Tools for Ecosystem and Resources (LOBSTER) model (Float64) 
 Light attenuation: Two-band light attenuation model (Float64)
 Sediment: Nothing
 Particles: Nothing

julia> bgc_model.underlying_biogeochemistry
Lodyc-DAMTP Ocean Biogeochemical Simulation Tools for Ecosystem and Resources (LOBSTER) model (Float64) 
 Optional components:
    ├── Carbonates ✅ 
    ├── Oxygen ❌ 
    └── Variable Redfield Ratio ❌
 Sinking Velocities:
    ├── sPOM: 0.0 to -3.47e-5 m/s 
    └── bPOM: 0.0 to -0.0023148148148148147 m/s
```

Perhaps the summary should include slightly more information?

**Comment by navidcy** [comment]
I think it’s fine. Just wanted to ensure it wasn’t by accident. 

Merge at your convenience.

**Comment by jagoosw** [comment]
> I think it’s fine. Just wanted to ensure it wasn’t by accident.
> 
> Merge at your convenience.

Ah thank you, just saw this and have changed them a bit so will need to update docstrings

**Pull request merged**
