### PR TITLE
Add citation info in `README` + Docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by navidcy** [comment]
Perhaps we should add something in the Docs as well?

**Comment by jagoosw** [comment]
I guess so, probably just the exact same on the home page?

**Comment by jagoosw** [comment]
I think there is a mention about citing it on that page that can just be updated actually

**Comment by navidcy** [comment]
Yes, true. I’ll do that ;)

**Review by jagoosw — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
