### PR TITLE
Minor docs enhancements

### PR DESCRIPTION
**Pull request by navidcy**
This PR supercedes #85.

### CODE REVIEW

**Review by jagoosw — APPROVED** [review]
Thank you!

**Comment by jagoosw** [comment]
Thank you for all this! Are you happy for me to merge this and #92? I think you would normally be able to but because it's not run the tests you can't right?

**Comment by navidcy** [comment]
> Thank you for all this! Are you happy for me to merge this and #92? I think you would normally be able to but because it's not run the tests you can't right?

Sure. Merge!
Why didn’t the tests run though?

**Comment by jagoosw** [comment]
> > Thank you for all this! Are you happy for me to merge this and #92? I think you would normally be able to but because it's not run the tests you can't right?
> 
> Sure. Merge! Why didn’t the tests run though?

They're set to only run when `src` or `test` change. Its from when the repo was private so we had limited action minutes but I guess I may as well change it to run for all changes now

**Pull request merged**
