### PR TITLE
Reduce allocations

### LINKED ISSUE #104: Using `znode` instead of `znodes` inside kernels
https://github.com/OceanBioME/OceanBioME.jl/blob/888a107a6a95eb8531a72a958934cfbea4982081/src/Light/2band.jl#L16-L29

Here, I think it'd be much more efficient if instead of, e.g.,

```julia
zᶜ = znodes(grid, Center(), Center(), Center()) 
zᶜ[k + 1]
```

```Julia
using Oceananigans.Grids: znode
znode(i, j, k+1, grid, Center(), Center(), Center())
```

The former create a whole array and selects a value from it. The latter just gets the value needed from the `grid`.

### PR DESCRIPTION
**Pull request by navidcy**
Resolves #104

@jagoosw, are the `column_diffusion_timescale(model)` and the `update_TwoBandPhotosyntheticallyActiveRatiation!` being tested?

### CODE REVIEW

**Comment by jagoosw** [comment]
`update_TwoBandPhotosyntheticallyActiveRatiation!` is tested in `test/test_light.jl` but I don't think the timescale one is.

**Comment by navidcy** [comment]
OK, here are some benchmarks:

I run the following

```Julia
using Oceananigans, OceanBioME
using Oceananigans.Units
const year = years = 365days
@inline PAR⁰(x, y, t) = 60 * (1 - cos((t + 15days) * 2π / year)) * (1 / (1 + 0.2 * exp(-((mod(t, year) - 200days) / 50days)^2))) + 2
@inline H(t, t₀, t₁) = ifelse(t₀ < t < t₁, 1.0, 0.0)
@inline fmld1(t) = H(t, 50days, year) * (1 / (1 + exp(-(t - 100days) / 5days))) * (1 / (1 + exp((t - 330days) / 25days)))
@inline MLD(t) = - (10 + 340 * (1 - fmld1(year - eps(year)) * exp(-mod(t, year) / 25days) - fmld1(mod(t, year))))
@inline κₜ(x, y, z, t) = 1e-2 * (1 + tanh((z - MLD(t)) / 10)) / 2 + 1e-4
@inline temp(x, y, z, t) = 2.4 * cos(t * 2π / year + 50days) + 10
grid = RectilinearGrid(size=(1, 1, 5), x=(0, 10), y=(0, 3), z=[-1, -0.6, -0.5, -0.2, -0.19, 0])
model = NonhydrostaticModel(; grid,
                              closure = ScalarDiffusivity(ν = κₜ, κ = κₜ), 
                              biogeochemistry = LOBSTER(; grid,
                                                          surface_phytosynthetically_active_radiation = PAR⁰,
                                                          carbonates = true,
                                                          advection_schemes = (sPOM = WENO(grid), bPOM = WENO(grid))),
                              advection = nothing)

using BenchmarkTools
@btime column_diffusion_timescale(model)
```

and I get

**Comment by navidcy** [comment]
That the number is the same on `main` and here it's soothing. Perhaps we should add a test?

**Comment by navidcy** [comment]
ok, have a look at your convenience :)

**Review by jagoosw — APPROVED** [review]
All lgtm, thank you!

Yeah it might be a good idea for us to add tests for it. I think I held off on improving the timestep stuff because once https://github.com/CliMA/Oceananigans.jl/pull/3027 is merged I think there are better fixes for working out the advection timescale with sinking particles (although this doesn't apply to the diffusion timescale here). 

Edit: linked wrong PR

**Pull request merged**
