### PR TITLE
Better latex rendering in docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by jagoosw** [comment]
Thank you! I'm not sure why the docs build isn't working but will fix when I'm back.

**Comment by jagoosw** [comment]
I can't checkout this branch so can't update with the changes to main, so if you can do that it would be great please!

**Comment by jagoosw** [comment]
Also I'll add permissions so you can make branches in this repo

**Comment by navidcy** [comment]
It may be related to #92

**Pull request closed without merging**
