### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by navidcy**
This PR fixes a few things in the docs.

- Cleaner visualization for the README example
- Converts doctests to examples: The doctests are not appropriate since output includes time it takes for a simulation to run (that varies on each machine) or figures. Also the doctest syntax was wrong; there was a space after the three backticks.
- Fixes figure not showing in the "Quick start" section.
- Fixes few typos

Supersedes #99 

preview at https://oceanbiome.github.io/OceanBioME.jl/previews/PR100/

### CODE REVIEW

**Comment by navidcy** [comment]
I was thinking that we can make the example in the Docs actually run with the docs built by converting that to an `@example`.

**Comment by navidcy** [comment]
OK, now this _is_ ready for review!

**Review by johnryantaylor — APPROVED** [review]
@navidcy, thank you very much for these edits to the example code.  The movie also looks much nicer now!

**Review by jagoosw — APPROVED** [review]
Thank you very much, these look great!

**Pull request merged**
