### PR TITLE
Update Oceananigans dependency + run CI and Docs on julia v1.9

### PR DESCRIPTION
**Pull request by navidcy**
@jagoosw, is updating to Oceananigans v0.84.1 a good idea?

### CODE REVIEW

**Comment by jagoosw** [comment]
Yeah seems like a good idea. I'm thinking for merging all the current PRs, if I do #124 and #123 which are non-breaking and quite simple, then #121, then fix the conflicts here and bump the version here?

**Review by jagoosw — APPROVED** [review]
lgtm

**Comment by navidcy** [comment]
> Yeah seems like a good idea. I'm thinking for merging all the current PRs, if I do #124 and #123 which are non-breaking and quite simple, then #121, then fix the conflicts here and bump the version here?

is it a breaking change?

**Comment by navidcy** [comment]
OK, I think we are hitting this: https://github.com/CliMA/Oceananigans.jl/issues/3184 and tests fail on v1.8.

**Comment by navidcy** [comment]
So on second thought, post v0.84.1 Oceananigans is _only_ tested on Julia v1.9. So perhaps it's safer to drop v1.8?

**Comment by jagoosw** [comment]
Yeah I'm happy to drop 1.8 support

**Comment by jagoosw** [comment]
> > Yeah seems like a good idea. I'm thinking for merging all the current PRs, if I do #124 and #123 which are non-breaking and quite simple, then #121, then fix the conflicts here and bump the version here?
> 
> is it a breaking change?

The sediment stuff defiantly breaks the sediment API, I guess this isn't breaking though so could do this first then release on #121

**Comment by navidcy** [comment]
Well it would be breaking if we drop v1.8! :)

**Comment by navidcy** [comment]
I don't know why there is the 

> Julia 1.8 - ubuntu-latest - x64 - pull_request Expected — Waiting for status to be reported

That shouldn't be there. I removed those tests... I'll merge when everything else passes.

**Comment by jagoosw** [comment]
I think its because the branch protection rule is specific to the 1.8 test, I've changed it to the 1.9 workflow now so I'm not sure why its still there. So yeah bypass the rule and I think it should work for the next PR

**Pull request merged**
