### PR TITLE
Ensure that all `.jld2`/`.nc` files are deleted before docs deployment

### PR DESCRIPTION
**Pull request by navidcy**
Related to #90.

x-ref: https://github.com/CliMA/Oceananigans.jl/pull/3109

### CODE REVIEW

**Comment by navidcy** [comment]
ok, this is ready for review :)

**Comment by navidcy** [comment]
x-ref: https://github.com/CliMA/Oceananigans.jl/pull/3113

**Review by jagoosw — APPROVED** [review]
Thanks!

**Comment by jagoosw** [comment]
No idea why this failed, if I run it locally it works fine

**Comment by navidcy** [comment]
We get the same issues in https://github.com/CliMA/Oceananigans.jl/pull/3109. Let me figure it out there and I'll deal with this after.

**Comment by jagoosw** [comment]
> We get the same issues in https://github.com/CliMA/Oceananigans.jl/pull/3109. Let me figure it out there and I'll deal with this after.

Thanks!

**Pull request merged**
